---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - My Github repos:
        - abbr: GH
          href: https://github.com/mathisschmidt?tab=repositories

- Social:
    - Reddit:
        - abbr: RE
          href: https://reddit.com/

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/

- To keep somewhere:
    - dashboardicons: 
        - href: https://dashboardicons.com/
