---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Server management:
    - Nginx:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/nginx-proxy-manager.png
        href: http://141.94.21.234:81/
        description: Reverse proxy manager
    - Cloudflare:
        icon: cloudflare.png
        href: https://dash.cloudflare.com/3b01aeef64fcd7dbcfcf0e8307ef1e0e/mathisschmidt.com
        description: DNS management
    - Portainer:
        icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/portainer-dark.svg
        href: https://portainer.mathisschmidt.com/
        description: Docker management
    - Central room:
        href: https://204.168.225.39:9090/

- My self hosted services:
    - Actual budget:
        icon: actual-budget.png
        href: https://actualbudget.mathisschmidt.com/
        description: My actual budget instance.
    - Seafile:
        icon: seafile.svg
        href: https://seafile.mathisschmidt.com
    - "IDFC: PDF -> CSV":
        href: http://204.168.225.39:1007/
    - "My-world":
        href: https://mathisschmidt.com
